name: "Valid XML"
author: "action-pack"
description: "Action to verify XML files. Files are found within a directory and subdirectories with matching file endings."
branding:
  icon: "check-circle"
  color: "gray-dark"

inputs:
  path:
    description: "Path to scan"
    default: "/"
  file-endings:
    description: "Comma-separated file endings that are checked to be valid XML files. Capitalization is ignored."
    default: ".xml"

outputs:
  result:
    description: "Error message with file name, line, column and error. Or a success message with the count of verified files."

runs:
  using: node20
  main: dist/index.js
